version: '2.1'

services:
  colormicroservices:
    image: colormicroservice
    build: .
    ports:
      - 3000:3000
  colorapp:
    image: colorapp
    build: .
    ports:
      - 8888:3000
    environment:
      - COLORMICROSERVICE=http://localhost:3000/colors
